name: Deploy to Gigalixir

on:
  push:
    branches:
      - main  # 如果你的默认主分支叫 master，请修改此处

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 必须拉取完整的 Git 历史，否则 Gigalixir 无法识别变更

      - name: Deploy Application
        uses: gigalixir/gigalixir-action@v1
        with:
          gigalixir_email: ${{ secrets.GIGALIXIR_EMAIL }}
          gigalixir_api_key: ${{ secrets.GIGALIXIR_API_KEY }}
          gigalixir_app: ${{ secrets.GIGALIXIR_APP_NAME }}
